### ISSUE TITLE
Eliminating the use of "3rd mouse click" for functionality

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/map3d#42]

**Comment by bzenger** [comment]
In order to edit triangles (remove them) you need to use the "third mouse button click" across the triangle. On new versions of mac the third mouse button does not exist and it is impossible to actually get to implement. Can we modify to a different keystroke click?

**Comment by bryanworthen** [comment]
I'm sure that's very doable.

Any recommendations on which modifier and button?
A *long* time ago, a premise of using map3d was having a 3-button mouse (even if you had a mac that came with a 1-button mouse).

**Comment by bzenger** [comment]
Haha that is awesome. At this point, I cannot even get the 3rd button to configure even if I do have a 3 button mouse. Right now the problem is when creating meshes and editing meshes in map3d. To delete the triangles or edges you need the middle button. The easiest solution in my mind would be a command right click or something like that in that specific mode. I don’t know how many other modes use that 3rd mouse button so I wouldn’t know if there is a global replacement. 

Thanks Brian!

**Comment by bryanworthen** [comment]
Ok I fixed it.

I'll look at the user manual tomorrow. Don't know what it says.

It turns out the code was saying "Right click always turns on the menu" "but if you haven't handled events yet, and do ctrl-right-click handles the triangle deletion".

What sucks, of course, is that that the comment above it said "ctrl-middle-click does this".

Sigh.


So - make sure you do ctrl-right click, and if you don't have clipping planes on, you may not be able to select only one triangle.

(This is on master, not on a release)

**Comment by bzenger** [comment]
Works perfect! Thank you so much!
